package org.wdsl.witness.storage.room

import androidx.room.Entity
import androidx.room.PrimaryKey
import org.wdsl.witness.llm.LlmSummary
import org.wdsl.witness.model.LocationData

/**
 * Data class representing a recording entity in the Room database.
 *
 * @param id The unique identifier for the recording.
 * @param title The title of the recording.
 * @param recordingFileName The file name of the recording.
 * @param gpsPositions The list of GPS positions associated with the recording.
 * @param llmSummary An optional summary generated by a large language model (LLM).
 */
@Entity
data class Recording(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val recordingFileName: String,
    val gpsPositions: List<LocationData>,
    val llmSummary: LlmSummary? = null,
)
